### ISSUE TITLE
please update fabric 1.16.1

### ISSUE THREAD

**Issue by 18017894** [rikka0w0/LanServerProperties#1]
please update fabric 1.16.1,I want to play with my friends.pls

**Comment by Eric-01** [comment]
Just come back to Forge, there is nothing wrong with it. If you were able to switch to Rift/Fabric without notable problems, return to Forge will be much less problematic ;)

**Comment by 18017894** [comment]
But I have a server, there's many mods just can use Fabric, so can you pls update it?:-D

**Comment by Eric-01** [comment]
I'm not the developer of this mod, so it rather doesn't depend on me whether this mod will support other APIs than the Forge's ones or not.

If you wish, in the meanwhile I can willingly try to provide you Forge counterparts of the mods you are using now.

**Comment by Eric-01** [comment]
I'm not the developer of this mod, so it rather doesn't depend on me, whether this mod will support other APIs than the Forge's ones or not.

If you wish, in the meanwhile I can willingly try to provide you Forge counterparts of the mods you are using now. Simply give me the list :)

**Comment by 18017894** [comment]
I think I should make this mod compatible by myself
