### ISSUE TITLE
非常感谢作者大大

### ISSUE THREAD

**Issue by StudentWeis** [rikka0w0/LanServerProperties#12]
非常感谢作者大大制作这个模组并持续更新，我使用您的源码编译了 1.17 Fabric 版本，**请问**我是否可以将其发布在 Bilibili 网站上，并做一些介绍？我会留下您的署名、Github 仓库地址和 CurseForge 模组链接~

**Comment by rikka0w0** [comment]
可以的~

如果可能的话优先给CurseForge和MCBBS的下载地址w
https://www.curseforge.com/minecraft/mc-mods/lan-server-properties/files/3414104
https://www.curseforge.com/minecraft/mc-mods/lan-server-properties/files/3414106

https://www.mcbbs.net/forum.php?mod=viewthread&tid=1056335&page=1&extra=#pid18446032

Github Release的也可以给，但是当备用的就会w

视频发布之后，可否提供链接？我把链接放到这里方便大家安装使用。谢啦
