### ISSUE TITLE
如何在快照上使用

### ISSUE THREAD

**Issue by mizoreyo** [rikka0w0/LanServerProperties#14]
Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Replace 'Minecraft' (minecraft) 1.18-alpha.21.43.a with 'Minecraft' (minecraft) 1.17- (later versions might work too).
Unmet dependency listing:
Mod 'Lan Server Properties' (lanserverproperties) requires "any 1.17.x version" of 'Minecraft' (minecraft), but only the wrong version is present: 1.18-alpha.21.43.a!
'Minecraft' (minecraft) 1.18-alpha.21.43.a is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
'Minecraft' (minecraft) 1.18-alpha.21.43.a, reason: to replace
<html>at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)<br/>at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>

**Comment by rikka0w0** [comment]
I don't have time to work on a 1.18 version yet. But I think you can compile your own 1.18 version.
You need to clone the repo and follow the instructions in `readme.md`.
You need to edit this file:
https://github.com/rikka0w0/LanServerProperties/blob/master/fabric/gradle.properties

**Comment by mizoreyo** [comment]
Thank you

**Comment by rikka0w0** [comment]
1.18.x has been officially supported
