### ISSUE TITLE
1.16.5版本使用Java16+会导致mod失效

### ISSUE THREAD

**Issue by Dr-WeiAL** [rikka0w0/LanServerProperties#15]
#9 就是这个导致的

**Comment by sjc0910** [comment]
实际上java15也不行，得用java11

**Comment by rikka0w0** [comment]
找到问题了，因为java16对反射的安全限制更多，原来的方法不能用了，这个问题在1.17.1上解决了。如果1.16.5的话就用java8吧，说实话我没测试过1.16.5配高于8的java会发生啥。。
