### ISSUE TITLE
非常感谢作者大佬的开发，关于ip地址变更问题

### ISSUE THREAD

**Issue by LsaNa1s** [rikka0w0/LanServerProperties#16]
在从家到学校之后，进入游戏开启对局域网开放之后，左下角的ip地址显示已开发端口还是家里的ip地址而未能变更为学校的ip地址，故想问问作者大佬，在哪能进行修改呢

**Comment by rikka0w0** [comment]
家里和学校都是内网，给你ip的是当地路由器的DHCP服务器。用那个地址是可以做到宿舍或者家里联机的。如果需要让外面的人进来，要么用ipv6要么用SakuraFRP之类的转发
