### ISSUE TITLE
The LanServerProperties 1.9 NOT Running in the latest of Forge (41.0.96)

### ISSUE THREAD

**Issue by MuCloudOfficial** [rikka0w0/LanServerProperties#20]
The Error : __java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ScreenEvent$InitScreenEvent$Post__  
This Error occured in your java file :  ___LanServerProperties.java:75___  
___at rikka.lanserverproperties.LanServerProperties$ClientHandler.registerGuiEventHandler___  
  
Please fix this Problem. thanks.

**Comment by MuCloudOfficial** [comment]
It can running in the Forge 41.0.42  
But it not running in the Forge 41.0.96

**Comment by rikka0w0** [comment]
Working on a fix, thanks for reporting the problem

**Comment by rikka0w0** [comment]
A breaking change inside Forge itself causes the problem. As of 2022 07 27, Forge does not yet have a stable release for MC 1.19, so this kind of breaking changes should be expected. Check out this:
https://github.com/rikka0w0/LanServerProperties/releases/tag/1.9.1_Forge

This should fix the problem. Can you try running this mod on MC 1.19.1 to see if it works?

**Comment by MuCloudOfficial** [comment]
Got it. Thanks.

**Comment by MuCloudOfficial** [comment]
> A breaking change inside Forge itself causes the problem. As of 2022 07 27, Forge does not yet have a stable release for MC 1.19, so this kind of breaking changes should be expected. Check out this: https://github.com/rikka0w0/LanServerProperties/releases/tag/1.9.1_Forge
> 
> This should fix the problem. Can you try running this mod on MC 1.19.1 to see if it works?

Not yet, I will try later.
