### ISSUE TITLE
How should I allow fights

### ISSUE THREAD

**Issue by SilianZ** [rikka0w0/LanServerProperties#25]
I am using this mod to connect with my friend, but there is no "allow fight" option in the setting, which leads to that when I use the “Majo's broom” with him, I will always be kicked out for the reason of "Flying is not enabled on this server".
*I don't know how to open a server.

**Comment by rikka0w0** [comment]
Which version are you using?

**Comment by SilianZ** [comment]
I don't know much, this is I help other people to ask.
不知道，这是我帮别人问的。
