### ISSUE TITLE
1.20 Forge version 

### ISSUE THREAD

**Issue by TamimZaman99** [rikka0w0/LanServerProperties#31]
When are you gonna work on the 1.20 forge version? I really need this mod right now

**Comment by WuJunkai2004** [comment]
1.20 may use this 
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN

**Comment by rikka0w0** [comment]
我正在做

**Comment by rikka0w0** [comment]
> When are you gonna work on the 1.20 forge version? I really need this mod right now

Checkout:
https://github.com/rikka0w0/LanServerProperties/releases/tag/1.11_Forge_Fabric
