### ISSUE TITLE
about the mod

### ISSUE THREAD

**Issue by Rogenar** [rikka0w0/LanServerProperties#33]
With this mod, will I be able to play multiplayer with my friends just by sharing the port?

**Comment by rikka0w0** [comment]
> With this mod, will I be able to play multiplayer with my friends just by sharing the port?

True if your friends are on the same LAN with you, i.e. they are in your home. Otherwise, regardless of IPv4 or IPv6, there will be at least one firewall/NAT between you and your friend, which you need to configure.
