### ISSUE TITLE
Text in UI not loaded

### ISSUE THREAD

**Issue by saintech** [rikka0w0/LanServerProperties#34]
Versions:
```
LanServerProperties: 1.11 (Fabric)
Minecraft: 1.20.1
LWJGL 3: 3.3.1
Fabric Loader: 0.14.21
```
![image](https://github.com/rikka0w0/LanServerProperties/assets/4853612/9697469b-41dc-4e47-a146-73159f3e050a)

**Comment by rikka0w0** [comment]
You need to install Fabric API as well

**Comment by saintech** [comment]
> You need to install Fabric API as well

@rikka0w0 it works now, thank you.

The README says "Fabric API is optional", but it doesn't seem to be the case.
