### ISSUE TITLE
1.20fabric版本关闭在线登录模式有问题

### ISSUE THREAD

**Issue by Alioth-1701** [rikka0w0/LanServerProperties#36]
![A061DA135CFD93BBD9EA0EE4BCD15115](https://github.com/rikka0w0/LanServerProperties/assets/117868014/a70b5212-7030-444b-a23f-b348ff969784)
我在模组包中添加之后，关闭在线登录验证之后打开局域网服务器，使用了Sakura frp进行了内网穿透，然后加入的服务器的玩家无法使用离线登录，这时切换成在线登录的情况能够顺利进入。
具体报错情况如图，麻烦问问可能是模组设置的问题，还是模组包设置的问题，还是本身网络环境可能出现的问题，感谢

**Comment by rikka0w0** [comment]
可以提供一下客户端和服务端的日志不，我来看一下错误信息，有可能是和其他模组有冲突

**Comment by rikka0w0** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/lan-server-properties/files/4776656
应该已经修复
