### ISSUE TITLE
离线模式+UUID修复似乎不工作

### ISSUE THREAD

**Issue by 2045632193** [rikka0w0/LanServerProperties#39]
Mod版本**1.8** 游戏版本**1.18.2**

原本局域网联机是开的正版验证，然后因为有个人也想加入，并且他没有正版，所以说就想开UUID修复+离线模式，但是并**不工作**。

根据mod简介的预期情况：正版用户应该会使用正版UUID,并且会**保留背包**
实际情况：正版用户也使用离线UUID,并且**不保留背包**

**Comment by 2045632193** [comment]
@rikka0w0

**Comment by rikka0w0** [comment]
是forge还是fabric版本的

**Comment by rikka0w0** [comment]
另外前一段时间国内访问mojang正版验证api不正常，修复模式下获取正版uuid是需要连mojang正版验证api的，如果连接不上去就会退回离线uuid。现在据说大部分都恢复了，那这个功能应该也没问题了。实在不行开服的人那边代理一下mojang的api即可。
