### ISSUE TITLE
i18n错误

### ISSUE THREAD

**Issue by todest** [rikka0w0/LanServerProperties#6]
Release版本：1.4, For Fabric 1.16.2, 1.16.3
MC版本：1.16.4，Fabric
![](https://user-images.githubusercontent.com/33983947/103148565-0b00bc80-479c-11eb-9a8d-a1f193e31618.png)

**Comment by rikka0w0** [comment]
试试英文模式，能不能显示文字，可能是我本地化没做好

**Comment by todest** [comment]
> 试试英文模式，能不能显示文字，可能是我本地化没做好
![L_TRIKD1MSE SMY91335A3L](https://user-images.githubusercontent.com/33983947/107184756-20643a00-6a1c-11eb-955f-5423e1a06adf.png)
英文模式也是这样，但是加上fabric api之后就都正常了。
