### ISSUE TITLE
1.17 compatibility

### ISSUE THREAD

**Issue by Enderbot5** [rikka0w0/LanServerProperties#8]

**Comment by Eric-01** [comment]
Forge hasn't even been released for 1.17.x yet.

**Comment by Eric-01** [comment]
Forge hasn't even been publicly released for 1.17.x yet.

**Comment by zwamdurkel** [comment]
Fabric has been released though

**Comment by Eric-01** [comment]
Yes, it did. But who would like to install anything other than Forge on the server side? ;p And this mod has to be installed on the server side.

**Comment by rikka0w0** [comment]
1.17.1 Forge and Fabric

https://github.com/rikka0w0/LanServerProperties/releases/tag/1.5_Forge_Fabric
