### ISSUE TITLE
无法固定端口，和离线模式无法开始

### ISSUE THREAD

**Issue by xingcsz** [rikka0w0/LanServerProperties#9]
1.16.5forge下，模组版本1.4下，无法固定端口为25565，也无法固定其它端口，但模组有加载，而且离线模式无法开启

**Comment by rikka0w0** [comment]
试试curseforge上的版本
https://www.curseforge.com/minecraft/mc-mods/lan-server-properties/files

如果还不行提供下Forge版本以及mod列表，蟹蟹！

**Comment by sjc0910** [comment]
我也遇到了，用curseforge的也不行

**Comment by ZuanXu** [comment]
me too，我开联机的时候，sjc0910进不去。

**Comment by xuwuwudi** [comment]
同样的问题
![K18(IWHRR{@ %1ZJSNT4I4A](https://user-images.githubusercontent.com/84704462/128621763-9fe58014-43ec-41a6-95c7-1a5fb391c1c3.png)
![6G$}) OA94(UU{`$TK~C @X](https://user-images.githubusercontent.com/84704462/128621766-7b1152cc-c21f-4223-bef8-d6972291e956.png)
启动器PCL2  至于java我用的16，不知道影不影响

**Comment by sjc0910** [comment]
最新版的forge好像没这个问题了
![image](https://user-images.githubusercontent.com/59308466/129131978-2b0ee898-6be3-43e0-bcf5-e499392ba660.png)

**Comment by Duoq233** [comment]
前几天换成java16就出现端口无法固定，今天换回java11问题已经解决了

**Comment by rikka0w0** [comment]
找到问题了，因为java16对反射的安全限制更多，原来的方法不能用了，这个问题在1.17.1上解决了。如果1.16.5的话就用java8吧，说实话我没测试过1.16.5配高于8的java会发生啥。。
